### ISSUE TITLE
Add Curl Follow Redirect.

### ISSUE THREAD

**Issue by joeyboli** [oleh-exe/Mp3StreamTitle#4]
Add Curl Follow Redirect To support zeno.fm links

curl_setopt($ch, CURLOPT_FOLLOWLOCATION, true);

**Comment by oleh-exe** [comment]
Hi! 
Did it help you? It didn't help me.

**Comment by joeyboli** [comment]
Yes it did, I was able to create an api using your library.

**Comment by joeyboli** [comment]
> Hi! Did it help you? It didn't help me.

API endpoint https://api.streamafrica.net/zeno/new.php?id=hca68918n98uv

The ?id=   payload is the zeno mountpoint name.

**Comment by oleh-exe** [comment]
Hi, I have added: 
`curl_setopt($ch, CURLOPT_FOLLOWLOCATION, true);`

Thank you! 

And sorry, I saw your fork late...

**Comment by joeyboli** [comment]
> `curl_setopt($ch, CURLOPT_FOLLOWLOCATION, true);`

Thanks for adding it. :)
